# Generated by Django 6.0.6 on 2026-07-24 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
            ],
            options={
                'verbose_name': 'Тип учреждения',
                'verbose_name_plural': 'Типы учреждений',
                'db_table': 'institution_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', help_text='Официальное полное наименование учреждения', max_length=255, verbose_name='Полное наименование')),
                ('short_name', models.CharField(db_column='short_name', help_text='Сокращённое название, используемое в списках и отчётах', max_length=100, verbose_name='Краткое название')),
                ('address', models.TextField(db_column='address', help_text='Юридический и/или фактический адрес', verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', verbose_name='Дата обновления')),
                ('institution_type', models.ForeignKey(db_column='institution_type_id', help_text='Ссылка на тип учреждения из справочника', on_delete=django.db.models.deletion.PROTECT, to='institutions.institutiontype', verbose_name='Тип учреждения')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'db_table': 'institutions',
                'ordering': ('short_name',),
                'managed': True,
            },
        ),
    ]
