# Generated by Django 6.0.6 on 2026-07-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisoryAuthority',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Надзорный орган',
                'verbose_name_plural': 'Надзорные органы',
                'db_table': 'supervisory_authorities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
                'db_table': 'violations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(db_column='number', max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('IN_PROGRESS', 'В работе'), ('EXPIRING', 'Истекает'), ('COMPLETED', 'Выполнено'), ('OVERDUE', 'Просрочено')], db_column='status', default='NEW', max_length=20)),
                ('issue_date', models.DateField(db_column='issue_date')),
                ('deadline_date', models.DateField(db_column='deadline_date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('created_by_user', models.ForeignKey(db_column='created_by_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(db_column='institution_id', on_delete=django.db.models.deletion.CASCADE, to='institutions.institution')),
                ('authority', models.ForeignKey(db_column='authority_id', on_delete=django.db.models.deletion.CASCADE, to='prescriptions.supervisoryauthority')),
            ],
            options={
                'verbose_name': 'Предписание',
                'verbose_name_plural': 'Предписания',
                'db_table': 'orders',
                'ordering': ('-created_at',),
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('original_filename', models.CharField(db_column='original_filename', max_length=255)),
                ('file_path', models.TextField(db_column='file_path')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('uploaded_by_user', models.ForeignKey(db_column='uploaded_by_user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='prescriptions.order')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'db_table': 'files',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderViolation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, related_name='order_violations', to='prescriptions.order')),
                ('violation', models.ForeignKey(db_column='violation_id', on_delete=django.db.models.deletion.CASCADE, to='prescriptions.violation')),
            ],
            options={
                'verbose_name': 'Связь предписания и нарушения',
                'verbose_name_plural': 'Связи предписаний и нарушений',
                'db_table': 'order_violations',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='idx_orders_status'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['deadline_date'], name='idx_orders_deadline'),
        ),
        migrations.AlterUniqueTogether(
            name='orderviolation',
            unique_together={('order', 'violation')},
        ),
    ]
