# Generated by Django 5.2.15 on 2026-06-09 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название надзорного органа')),
            ],
            options={
                'verbose_name': 'Надзорный орган',
                'verbose_name_plural': 'Надзорные органы',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер предписания')),
                ('issuance_date', models.DateField(verbose_name='Дата выдачи')),
                ('deadline_date', models.DateField(verbose_name='Срок исполнения')),
                ('year', models.IntegerField(choices=[(2024, '2024'), (2025, '2025')], verbose_name='Год')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.authority', verbose_name='Надзорный орган')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.institution', verbose_name='Учреждение')),
                ('responsible_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institutions.employee', verbose_name='Ответственный сотрудник')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prescriptions.status', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Предписание',
                'verbose_name_plural': 'Предписания',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='prescriptions.order')),
            ],
            options={
                'verbose_name': 'Нарушение',
                'verbose_name_plural': 'Нарушения',
            },
        ),
    ]
