# Generated by Django 6.0.6 on 2026-09-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(db_column='number', max_length=100, unique=True),
        ),
    ]
